name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build executable
      run: npm run build

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: dot-graph-viewer-exe
        path: dist/*.exe
